#cloud-config
package_upgrade: true
packages:
  - apache2
runcmd:
  - echo '<h1>Homepage de Rodrigo Salvado</h1>' | sudo tee /var/www/html/index.html > /dev/null
  - sudo systemctl enable apache2
  - sudo systemctl start apache2